### ISSUE TITLE
Unable to install module from FoundryVTT "Install" button or with Manifest URL

### ISSUE THREAD

**Issue by Redblast1** [Chrisrous/Chris-Sound-Module#1]
Hi- was looking to try out the module and could not install it. 

When clicking install from the Install Module window in the setup screen. 
![image](https://github.com/user-attachments/assets/c65e6625-2b34-42f5-91e0-402318864817)

I have tried the Manifest URL from the packages page on FoundryVTT's site, the URL: https://raw.githubusercontent.com/Chrisrous/Chris-Sound-Module/main/module.json

This returns the same error for me. Not sure if the JSON file is missing a few lines that could be causing this? Checking a different module manifest JSON file I am seeing lines with "manifest" "url" and "download", but these are not present for the Crhis Sound Module. I am not a developer so I do not know for sure. 

I have not tried a manual install yet. 

Using FoundryVTT on a home Ubuntu server, Version 12 Stable, Build 330.

Thank you,

**Comment by Chrisrous** [comment]
Hi @Redblast1 you were right.
I forgot to include the download links in the module.json file. I have now added them and successfully tested it. The module can now be downloaded via Foundry.

Thanks for the info.
